### ISSUE TITLE
Support for WildFly Kubernetes operator

### ISSUE THREAD

**Issue by jamesnetherton** [wildfly-extras/wildfly-camel#2825]
It'd be nice to have some support / documentation around running WFC with the WildFly Operator:

https://github.com/wildfly/wildfly-operator

Should simplify running WFC on Kubernetes / OpenShift somewhat. E.g by deploying a custom resource:

```yaml
apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: wildfly-camel-test
spec:
  applicationImage: "docker.io/wildflyext/wildfly-camel:16.0.0"
  size: 3
```
